/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jules
 */
public class master_mind extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(master_mind.class.getName());
    private jeucadenas jeu = new jeucadenas();
    private int[] saisie = {0, 0, 0, 0};

    /**
     * Creates new form master_mind
     */
    public master_mind() {
        initComponents();
        initialiserInterface();
        jeu = new jeucadenas();
    }    
    private void initialiserInterface() {
    texte_intro.setText("Devinez la combinaison !");
    texte_score.setText("Tentatives : 0");

    // valeurs affichées pour les 4 chiffres
    texte_chiffre0.setText("" + saisie[0]);
    texte_chiffre1.setText("" + saisie[1]);
    texte_chiffre2.setText("" + saisie[2]);
    texte_chiffre3.setText("" + saisie[3]);

    texte_lbl_nb_chiffres_exacts.setText("Chiffres exacts :");
    texte_lbl_nb_chiffres_haut.setText("Trop hauts :");
    texte_lbl_nb_chiffres_bas.setText("Trop bas :");

    texte_nb_chiffres_exacts.setText("0");
    texte_nb_chiffres_haut.setText("0");
    texte_nb_chiffres_bas.setText("0");
}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre1 = new javax.swing.JButton();
        up_chiffre2 = new javax.swing.JButton();
        up_chiffre3 = new javax.swing.JButton();
        up_chiffre4 = new javax.swing.JButton();
        texte_chiffre0 = new javax.swing.JLabel();
        texte_chiffre1 = new javax.swing.JLabel();
        texte_chiffre2 = new javax.swing.JLabel();
        texte_chiffre3 = new javax.swing.JLabel();
        down_chiffre1 = new javax.swing.JButton();
        down_chiffre2 = new javax.swing.JButton();
        down_chiffre3 = new javax.swing.JButton();
        down_chiffre4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("trouver le code ");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        up_chiffre1.setText("/\\");
            up_chiffre1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, -1));

            up_chiffre2.setText("/\\");
                up_chiffre2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, -1));

                up_chiffre3.setText("/\\");
                    up_chiffre3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 60, -1));

                    up_chiffre4.setText("/\\");
                        up_chiffre4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 60, -1));

                        texte_chiffre0.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
                        texte_chiffre0.setText("0");
                        getContentPane().add(texte_chiffre0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 37, -1));

                        texte_chiffre1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
                        texte_chiffre1.setText("0");
                        getContentPane().add(texte_chiffre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 37, -1));

                        texte_chiffre2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
                        texte_chiffre2.setText("0");
                        getContentPane().add(texte_chiffre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 37, -1));

                        texte_chiffre3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
                        texte_chiffre3.setText("0");
                        getContentPane().add(texte_chiffre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 130, 20, -1));

                        down_chiffre1.setText("\\/");
                        down_chiffre1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, -1));

                        down_chiffre2.setText("\\/");
                        down_chiffre2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 60, -1));

                        down_chiffre3.setText("\\/");
                        down_chiffre3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, -1));

                        down_chiffre4.setText("\\/");
                        down_chiffre4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 60, -1));

                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

                        texte_lbl_nb_chiffres_exacts.setText("nombres de chiffres exactes :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 190, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 37, -1));

                        texte_lbl_nb_chiffres_haut.setText("nombre de chiffres trop haut : ");
                        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, -1));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 37, 20));

                        texte_lbl_nb_chiffres_bas.setText("nombre de chiffre trop bas : ");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, -1));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 37, -1));

                        texte_score.setText("0 sur 10 ");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 100, -1));

                        texte_tentatives.setText("Tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 100, 20));

                        bouton_recommencer.setText("recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre1ActionPerformed
        saisie[0] = (saisie[0] + 1) % 10;
        texte_chiffre0.setText("" + saisie[0]);
  // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre1ActionPerformed

    private void up_chiffre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre2ActionPerformed
        saisie[1] = (saisie[1] + 1) % 10;
        texte_chiffre1.setText("" + saisie[1]);
   // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre2ActionPerformed

    private void up_chiffre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre3ActionPerformed
        saisie[2] = (saisie[2] + 1) % 10;
        texte_chiffre2.setText("" + saisie[2]);
// TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre3ActionPerformed

    private void up_chiffre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre4ActionPerformed
        saisie[3] = (saisie[3] + 1) % 10;
        texte_chiffre3.setText("" + saisie[3]);
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre4ActionPerformed

    private void down_chiffre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre1ActionPerformed
        saisie[0] = (saisie[0] + 9) % 10; // -1 modulo 10
        texte_chiffre0.setText("" + saisie[0]);
    // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre1ActionPerformed

    private void down_chiffre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre2ActionPerformed
        saisie[1] = (saisie[1] + 9) % 10;
        texte_chiffre1.setText("" + saisie[1]);        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre2ActionPerformed

    private void down_chiffre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre3ActionPerformed
        saisie[2] = (saisie[2] + 9) % 10;
        texte_chiffre2.setText("" + saisie[2]);
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre3ActionPerformed

    private void down_chiffre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre4ActionPerformed
        saisie[3] = (saisie[3] + 9) % 10;
        texte_chiffre3.setText("" + saisie[3]);        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
       if (jeu.getNbTentatives() >= 10) { // limite à 10 tentatives
        texte_intro.setText("Partie terminée !");
        bouton_tester.setEnabled(false);
        return;
    }

    int[] resultat = jeu.verifier(saisie);

    texte_nb_chiffres_exacts.setText("" + resultat[0]);
    texte_nb_chiffres_haut.setText("" + resultat[1]);
    texte_nb_chiffres_bas.setText("" + resultat[2]);

    // Met à jour le label avec le format "X sur 10"
    texte_score.setText(jeu.getNbTentatives() + " sur 10");

    if (jeu.isGagne()) {
        texte_intro.setText("Bravo, vous avez trouvé !");
        bouton_tester.setEnabled(false);
    }

 // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
      jeu.reinitialiser();

        saisie = new int[]{0,0,0,0};

        texte_chiffre0.setText("0");
        texte_chiffre1.setText("0");
        texte_chiffre2.setText("0");
        texte_chiffre3.setText("0");

        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_haut.setText("0");
        texte_nb_chiffres_bas.setText("0");

        texte_score.setText("0 sur 10");

        texte_intro.setText("Nouvelle partie !");

        bouton_tester.setEnabled(true);
  // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new master_mind().setVisible(true));    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre1;
    private javax.swing.JButton down_chiffre2;
    private javax.swing.JButton down_chiffre3;
    private javax.swing.JButton down_chiffre4;
    private javax.swing.JLabel texte_chiffre0;
    private javax.swing.JLabel texte_chiffre1;
    private javax.swing.JLabel texte_chiffre2;
    private javax.swing.JLabel texte_chiffre3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre1;
    private javax.swing.JButton up_chiffre2;
    private javax.swing.JButton up_chiffre3;
    private javax.swing.JButton up_chiffre4;
    // End of variables declaration//GEN-END:variables
}