/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jules
 */
public class Fenetre_Quiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fenetre_Quiz.class.getName());
    private ArrayList<Question> questions;     
    private int indexQuestionCourante = 0;     

    /**
     * Creates new form Fenetre_Quiz
     */
    public Fenetre_Quiz() {
        initComponents();
        
       questions = new ArrayList<>();

        questions.add(new Question(
                "Qui se dort dessus depuis la rentrée",
                "Loubard", "Loan", "Mousitk", "Emir", 1));

        questions.add(new Question(
                "Qui a perdu l'aura betement avec Winston",
                "Samuel", "Loubiere", "Gros Thomas", "Arctique", 3));

        questions.add(new Question(
                "Qui a du mal au lit",
                "Basile", "Conrado ", "Ptit Thomas", "Moustik", 1));

        questions.add(new Question(
                "Qui est le meilleur du TDB ?",
                "Loan", "Basile", "Conrado", "Titou", 4));

        questions.add(new Question(
                "Depuis quand existe l'EPF ?",
                "56ans", "10^25ans", "2ans", "100ans", 4));

        afficherQuestionCourante();
        
        // Ajout des listeners sur les boutons
        bouton_rep1.addActionListener(e -> verifierReponse(1));
        boutton_rep2.addActionListener(e -> verifierReponse(2));
        bouton_rep3.addActionListener(e -> verifierReponse(3));
        bouton_rep4.addActionListener(e -> verifierReponse(4));
        bouton_quest_suivante.addActionListener(e -> questionSuivante());
    }
     private void afficherQuestionCourante() {
        Question q = questions.get(indexQuestionCourante);

        label_quuestion.setText(q.getIntitule());
        bouton_rep1.setText(q.getProposition1());
        boutton_rep2.setText(q.getProposition2());
        bouton_rep3.setText(q.getProposition3());
        bouton_rep4.setText(q.getProposition4());

        // Réactiver les boutons
        bouton_rep1.setEnabled(true);
        boutton_rep2.setEnabled(true);
        bouton_rep3.setEnabled(true);
        bouton_rep4.setEnabled(true);

        label_feedback.setText("");
    }
    private void verifierReponse(int numeroChoisi) {
        Question q = questions.get(indexQuestionCourante);

        if (numeroChoisi == q.getIndexBonneReponse()) {
            label_feedback.setText("Bonne réponse !");
            score++;
        } else {
            label_feedback.setText("Mauvaise réponse !");
        }

        label_score.setText("Score : " + score);

        // Désactiver boutons
        bouton_rep1.setEnabled(false);
        boutton_rep2.setEnabled(false);
        bouton_rep3.setEnabled(false);
        bouton_rep4.setEnabled(false);
    }
     private void questionSuivante() {
        indexQuestionCourante++;

        if (indexQuestionCourante < questions.size()) {
            afficherQuestionCourante();
        } else {
            label_quuestion.setText("Quiz terminé !");
            label_feedback.setText("Score final : " + score + " / " + questions.size());

            bouton_rep1.setEnabled(false);
            boutton_rep2.setEnabled(false);
            bouton_rep3.setEnabled(false);
            bouton_rep4.setEnabled(false);
            bouton_quest_suivante.setEnabled(false);
        }
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_quuestion = new javax.swing.JLabel();
        bouton_rep1 = new javax.swing.JButton();
        boutton_rep2 = new javax.swing.JButton();
        bouton_rep3 = new javax.swing.JButton();
        bouton_rep4 = new javax.swing.JButton();
        label_feedback = new javax.swing.JLabel();
        bouton_quest_suivante = new javax.swing.JButton();
        label_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_quuestion.setText("question");
        getContentPane().add(label_quuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 121, 50, -1));

        bouton_rep1.setText("jButton1");
        getContentPane().add(bouton_rep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        boutton_rep2.setText("jButton2");
        getContentPane().add(boutton_rep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        bouton_rep3.setText("jButton3");
        getContentPane().add(bouton_rep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        bouton_rep4.setText("jButton4");
        getContentPane().add(bouton_rep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        label_feedback.setText("reponse");
        getContentPane().add(label_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        bouton_quest_suivante.setText("questsuivante");
        getContentPane().add(bouton_quest_suivante, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        label_score.setText("score");
        getContentPane().add(label_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fenetre_Quiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_quest_suivante;
    private javax.swing.JButton bouton_rep1;
    private javax.swing.JButton bouton_rep3;
    private javax.swing.JButton bouton_rep4;
    private javax.swing.JButton boutton_rep2;
    private javax.swing.JLabel label_feedback;
    private javax.swing.JLabel label_quuestion;
    private javax.swing.JLabel label_score;
    // End of variables declaration//GEN-END:variables
}
