
import java.util.ArrayList;

    
    

    
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jules
 */
public class Fenetre_Quiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fenetre_Quiz.class.getName());
    private ArrayList<Question> questions ;
    int indexQuestionCourante = 0;
    int score = 0;

    /**
     * Creates new form Fenetre_Quiz
     */
    public Fenetre_Quiz() {
        initComponents();
        questions = new ArrayList<>();
    // Création des questions
    questions.add(new Question(
            "Qui se dort dessus depuis le debut de l'année ?",
            "Loubard", "loan", "Mathis", "Basile", 1));

    questions.add(new Question(
            "Qui a perdu betement de l'aura avec winston",
            "ptit thom", "moustik", "conrado", "gros thomas", 4));

    questions.add(new Question(
            "Depuis quand existe l'epf (ans) ?",
            "10^25", "25", "100", "56", 3));

    questions.add(new Question(
            "la salle ou cela vole le plus ?",
            "M104", "H08", "L104", "I01", 4));

    questions.add(new Question(
            "Le meilleur snack de montpellier ?",
            "Sun", "Roonys", "Raffine", "Intermarche clemencau", 4));

    afficherQuestionCourante(); }
    
    private void afficherQuestionCourante () {  
    Question q = questions.get(indexQuestionCourante);

    lblQuestion.setText(q.getIntitule());
    btnRep1.setText(q.getProposition1());
    btnRep2.setText(q.getProposition2());
    btnRep3.setText(q.getProposition3());
    btnRep4.setText(q.getProposition4());

    // Réactive les boutons
    btnRep1.setEnabled(true);
    btnRep2.setEnabled(true);
    btnRep3.setEnabled(true);
    btnRep4.setEnabled(true);

    lblFeedback.setText("");
    lblScore.setText("Score : " + score);
}
    private void verifierReponse(int choix) {

    Question q = questions.get(indexQuestionCourante);


    if (choix == q.getIndexBonneReponse()) {
        lblFeedback.setText("Bonne réponse !");
        score++;
        lblScore.setText("Score : " + score);
    } else {
        lblFeedback.setText("Mauvaise réponse !");
    }

    // Désactiver les boutons
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);
}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        btnSuivante = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setText("question");
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 350, -1));

        lblScore.setText("score");
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 94, -1));

        btnRep1.setText("rep1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 152, -1, -1));

        btnRep2.setText("rep2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        btnRep3.setText("rep3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        btnRep4.setText("rep4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        btnSuivante.setText("question suivante");
        btnSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuivante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        lblFeedback.setText("feedback");
        getContentPane().add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        verifierReponse(1); 
    }//GEN-LAST:event_btnRep1ActionPerformed
    private void btnSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivanteActionPerformed
         indexQuestionCourante++;

    if (indexQuestionCourante < questions.size()) {
    afficherQuestionCourante();

    } else {
          lblFeedback.setText("Quiz terminé ! Score final : " + score + " / " + Question.size());
          lblQuestion.setText("quiz fini");
        btnSuivante.setEnabled(false);
    }
    }//GEN-LAST:event_btnSuivanteActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        verifierReponse(2) ;
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        verifierReponse(3) ; 
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        verifierReponse(4) ;
    }//GEN-LAST:event_btnRep4ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fenetre_Quiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivante;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
